const FORBIDDEN_TIER_WORDS = ['premium', 'mid-premium', 'value tier'];
const BARE_IMPERATIVE_RE = /^(wipe|do not|don't|clean|dry|avoid|use|apply|dust|store|keep|remove|scrub)\b/i;
const RAW_DIMENSION_RE = /\b\d+(?:\.\d+)?\s*(?:m|cm|mm|in|inch|inches|ft|feet)\b\s*(?:[lwhd]\b)?(?:\s*x\s*\d+(?:\.\d+)?\s*(?:m|cm|mm|in|inch|inches|ft|feet)\b\s*(?:[lwhd]\b)?)+/i;

function normalize(v) {
  return String(v).trim().toLowerCase();
}

function includesNormalized(text, value) {
  return normalize(text).includes(normalize(value));
}

function validateItem(item, sourceProduct) {
  const errors = [];

  const requiredTopLevel = ['description', 'specifications', 'care_and_maintenance', 'warranty', 'returns', 'quality_promise'];
  for (const key of requiredTopLevel) {
    if (!(key in item) || item[key] === undefined || item[key] === null) {
      errors.push(`Missing top-level field: ${key}`);
    }
  }

  if (item.description) {
    for (const field of ['summary', 'aesthetic_style', 'texture', 'best_use']) {
      if (!item.description[field]) errors.push(`Missing description.${field}`);
    }
    // Summary should be 3-4 sentences.
    const summary = item.description.summary || '';
    const sentenceCount = (summary.match(/[.!?]/g) || []).length;
    if (sentenceCount < 3 || sentenceCount > 4) {
      errors.push(`description.summary should be 3-4 sentences; found ${sentenceCount}`);
    }
    if (RAW_DIMENSION_RE.test(summary)) {
      errors.push('description.summary must not include raw dimension strings');
    }

    if (sourceProduct) {
      if (sourceProduct.seating_capacity && !includesNormalized(summary, sourceProduct.seating_capacity)) {
        errors.push('description.summary must mention the selected size/seating variant');
      }
      if (sourceProduct.color_finish && !includesNormalized(summary, sourceProduct.color_finish)) {
        errors.push('description.summary must mention the selected color/finish variant');
      }

      if (Array.isArray(sourceProduct.available_sizes)) {
        const siblingSizes = sourceProduct.available_sizes.filter((size) => normalize(size) !== normalize(sourceProduct.seating_capacity));
        for (const size of siblingSizes) {
          if (!includesNormalized(summary, size)) {
            errors.push(`description.summary must mention sibling size variant "${size}"`);
          }
        }
      }

      if (Array.isArray(sourceProduct.available_colors)) {
        const siblingColors = sourceProduct.available_colors.filter((color) => normalize(color) !== normalize(sourceProduct.color_finish));
        for (const color of siblingColors) {
          if (!includesNormalized(summary, color)) {
            errors.push(`description.summary must mention sibling color variant "${color}"`);
          }
        }
      }
    }
  }

  // Specifications are NOT generated by the LLM; they are copied from source.
  // Validate that: 1) all values present match source exactly, 2) no extra
  // fields are added, 3) all non-empty source fields are present in output.
  if (item.specifications && sourceProduct) {
    const allowedSpecFields = ['dimensions', 'primary_material', 'weight', 'assembly_required', 'seating_capacity', 'color_finish'];
    // Check that all fields in item.specifications are allowed and match source.
    for (const field in item.specifications) {
      const generated = item.specifications[field];
      const source = sourceProduct[field];
      if (!allowedSpecFields.includes(field)) {
        errors.push(`specifications.${field} should not be generated; it is a source-copy-only field`);
      } else if (source === undefined || source === null || source === '') {
        errors.push(`specifications.${field} should not be present if missing in source`);
      } else if (normalize(generated) !== normalize(source)) {
        errors.push(`specifications.${field} does not match source data exactly`);
      }
    }
    // Check that all non-empty source fields are present in generated item.
    for (const field of allowedSpecFields) {
      if (sourceProduct[field] !== undefined && sourceProduct[field] !== null && sourceProduct[field] !== '') {
        if (!(field in item.specifications)) {
          errors.push(`specifications.${field} is present in source but missing in output`);
        }
      }
    }
  }

  // Field count checks
  if (item.care_and_maintenance) {
    const instructions = item.care_and_maintenance.instructions;
    const avoid = item.care_and_maintenance.avoid;
    if (!Array.isArray(instructions) || instructions.length !== 3) {
      errors.push('care_and_maintenance.instructions must have exactly 3 items');
    }
    if (!Array.isArray(avoid) || avoid.length !== 2) {
      errors.push('care_and_maintenance.avoid must have exactly 2 items');
    }
    for (const line of [...(instructions || []), ...(avoid || [])]) {
      if (typeof line === 'string' && BARE_IMPERATIVE_RE.test(line.trim())) {
        errors.push(`Polite-tone flag (bare imperative, human review can override): "${line}"`);
      }
    }
  } else {
    errors.push('Missing care_and_maintenance');
  }

  if (item.warranty) {
    const points = Array.isArray(item.warranty.points) ? item.warranty.points : [];
    if (points.length > 4) {
      errors.push('warranty.points must have at most 4 items');
    }
    if (!item.warranty.status_line || !/^\*\*(Yes|No)\*\*, it has a warranty of \*\*\d+\s+months\*\*\.$/.test(item.warranty.status_line.trim())) {
      errors.push('warranty.status_line must be exactly: "**Yes**, it has a warranty of **N months**." or "**No**, it has a warranty of **0 months**."');
    }
    if (points.length > 0 && points.some((point) => typeof point !== 'string' || !point.trim())) {
      errors.push('warranty.points must contain only non-empty strings');
    }
  } else {
    errors.push('Missing warranty');
  }

  if (item.returns) {
    if (!Array.isArray(item.returns.condition) || item.returns.condition.length !== 3) {
      errors.push('returns.condition must have exactly 3 items');
    }
  } else {
    errors.push('Missing returns');
  }

  // Tier leakage check — description must never reveal the internal price tier.
  const descriptionText = item.description ? JSON.stringify(item.description).toLowerCase() : '';
  for (const word of FORBIDDEN_TIER_WORDS) {
    if (descriptionText.includes(word)) {
      errors.push(`Tier leakage: description contains forbidden word "${word}"`);
    }
  }
  if (/[₹$]\s?\d/.test(descriptionText) || /\bprice\b/i.test(descriptionText)) {
    errors.push('Tier leakage: description appears to reference a price figure');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

module.exports = { validateItem };
